
with source as (

    select * from {{ source('DBT_DEMO', 'RAW_ENERGY') }}

),

renamed as (

    select
        "country" as country,
        "year" as year,
        "iso_code" as iso_code,
        "population" as population,
        "gdp" as gdp,
        --- this is a CI comment
        "biofuel_cons_change_pct" as biofuel_cons_change_pct,
        "biofuel_cons_change_twh" as biofuel_cons_change_twh,
        "biofuel_cons_per_capita" as biofuel_cons_per_capita,
        "biofuel_consumption" as biofuel_consumption,
        "biofuel_elec_per_capita" as biofuel_elec_per_capita,
        "biofuel_electricity" as biofuel_electricity,
        "biofuel_share_elec" as biofuel_share_elec,
        "biofuel_share_energy" as biofuel_share_energy,
        "carbon_intensity_elec" as carbon_intensity_elec,
        "coal_cons_change_pct" as coal_cons_change_pct,
        "coal_cons_change_twh" as coal_cons_change_twh,
        "coal_cons_per_capita" as coal_cons_per_capita,
        "coal_consumption" as coal_consumption,
        "coal_elec_per_capita" as coal_elec_per_capita,
        "coal_electricity" as coal_electricity,
        "coal_prod_change_pct" as coal_prod_change_pct,
        "coal_prod_change_twh" as coal_prod_change_twh,
        "coal_prod_per_capita" as coal_prod_per_capita,
        "coal_production" as coal_production,
        "coal_share_elec" as coal_share_elec,
        "coal_share_energy" as coal_share_energy,
        "electricity_demand" as electricity_demand,
        "electricity_generation" as electricity_generation,
        "energy_cons_change_pct" as energy_cons_change_pct,
        "energy_cons_change_twh" as energy_cons_change_twh,
        "energy_per_capita" as energy_per_capita,
        "energy_per_gdp" as energy_per_gdp,
        "fossil_cons_change_pct" as fossil_cons_change_pct,
        "fossil_cons_change_twh" as fossil_cons_change_twh,
        "fossil_elec_per_capita" as fossil_elec_per_capita,
        "fossil_electricity" as fossil_electricity,
        "fossil_energy_per_capita" as fossil_energy_per_capita,
        "fossil_fuel_consumption" as fossil_fuel_consumption,
        "fossil_share_elec" as fossil_share_elec,
        "fossil_share_energy" as fossil_share_energy,
        "gas_cons_change_pct" as gas_cons_change_pct,
        "gas_cons_change_twh" as gas_cons_change_twh,
        "gas_consumption" as gas_consumption,
        "gas_elec_per_capita" as gas_elec_per_capita,
        "gas_electricity" as gas_electricity,
        "gas_energy_per_capita" as gas_energy_per_capita,
        "gas_prod_change_pct" as gas_prod_change_pct,
        "gas_prod_change_twh" as gas_prod_change_twh,
        "gas_prod_per_capita" as gas_prod_per_capita,
        "gas_production" as gas_production,
        "gas_share_elec" as gas_share_elec,
        "gas_share_energy" as gas_share_energy,
        "greenhouse_gas_emissions" as greenhouse_gas_emissions,
        "hydro_cons_change_pct" as hydro_cons_change_pct,
        "hydro_cons_change_twh" as hydro_cons_change_twh,
        "hydro_consumption" as hydro_consumption,
        "hydro_elec_per_capita" as hydro_elec_per_capita,
        "hydro_electricity" as hydro_electricity,
        "hydro_energy_per_capita" as hydro_energy_per_capita,
        "hydro_share_elec" as hydro_share_elec,
        "hydro_share_energy" as hydro_share_energy,
        "low_carbon_cons_change_pct" as low_carbon_cons_change_pct,
        "low_carbon_cons_change_twh" as low_carbon_cons_change_twh,
        "low_carbon_consumption" as low_carbon_consumption,
        "low_carbon_elec_per_capita" as low_carbon_elec_per_capita,
        "low_carbon_electricity" as low_carbon_electricity,
        "low_carbon_energy_per_capita" as low_carbon_energy_per_capita,
        "low_carbon_share_elec" as low_carbon_share_elec,
        "low_carbon_share_energy" as low_carbon_share_energy,
        "net_elec_imports" as net_elec_imports,
        "net_elec_imports_share_demand" as net_elec_imports_share_demand,
        "nuclear_cons_change_pct" as nuclear_cons_change_pct,
        "nuclear_cons_change_twh" as nuclear_cons_change_twh,
        "nuclear_consumption" as nuclear_consumption,
        "nuclear_elec_per_capita" as nuclear_elec_per_capita,
        "nuclear_electricity" as nuclear_electricity,
        "nuclear_energy_per_capita" as nuclear_energy_per_capita,
        "nuclear_share_elec" as nuclear_share_elec,
        "nuclear_share_energy" as nuclear_share_energy,
        "oil_cons_change_pct" as oil_cons_change_pct,
        "oil_cons_change_twh" as oil_cons_change_twh,
        "oil_consumption" as oil_consumption,
        "oil_elec_per_capita" as oil_elec_per_capita,
        "oil_electricity" as oil_electricity,
        "oil_energy_per_capita" as oil_energy_per_capita,
        "oil_prod_change_pct" as oil_prod_change_pct,
        "oil_prod_change_twh" as oil_prod_change_twh,
        "oil_prod_per_capita" as oil_prod_per_capita,
        "oil_production" as oil_production,
        "oil_share_elec" as oil_share_elec,
        "oil_share_energy" as oil_share_energy,
        "other_renewable_consumption" as other_renewable_consumption,
        "other_renewable_electricity" as other_renewable_electricity,
        "other_renewable_exc_biofuel_electricity" as other_renewable_exc_biofuel_electricity,
        "other_renewables_cons_change_pct" as other_renewables_cons_change_pct,
        "other_renewables_cons_change_twh" as other_renewables_cons_change_twh,
        "other_renewables_elec_per_capita" as other_renewables_elec_per_capita,
        "other_renewables_elec_per_capita_exc_biofuel" as other_renewables_elec_per_capita_exc_biofuel,
        "other_renewables_energy_per_capita" as other_renewables_energy_per_capita,
        "other_renewables_share_elec" as other_renewables_share_elec,
        "other_renewables_share_elec_exc_biofuel" as other_renewables_share_elec_exc_biofuel,
        "other_renewables_share_energy" as other_renewables_share_energy,
        "per_capita_electricity" as per_capita_electricity,
        "primary_energy_consumption" as primary_energy_consumption,
        "renewables_cons_change_pct" as renewables_cons_change_pct,
        "renewables_cons_change_twh" as renewables_cons_change_twh,
        "renewables_consumption" as renewables_consumption,
        "renewables_elec_per_capita" as renewables_elec_per_capita,
        "renewables_electricity" as renewables_electricity,
        "renewables_energy_per_capita" as renewables_energy_per_capita,
        "renewables_share_elec" as renewables_share_elec,
        "renewables_share_energy" as renewables_share_energy,
        "solar_cons_change_pct" as solar_cons_change_pct,
        "solar_cons_change_twh" as solar_cons_change_twh,
        "solar_consumption" as solar_consumption,
        "solar_elec_per_capita" as solar_elec_per_capita,
        "solar_electricity" as solar_electricity,
        "solar_energy_per_capita" as solar_energy_per_capita,
        "solar_share_elec" as solar_share_elec,
        "solar_share_energy" as solar_share_energy,
        "wind_cons_change_pct" as wind_cons_change_pct,
        "wind_cons_change_twh" as wind_cons_change_twh,
        "wind_consumption" as wind_consumption,
        "wind_elec_per_capita" as wind_elec_per_capita,
        "wind_electricity" as wind_electricity,
        "wind_energy_per_capita" as wind_energy_per_capita,
        "wind_share_elec" as wind_share_elec,
        "wind_share_energy" as wind_sharee_energy
    from source

)

select * from renamed
